name: flutter_todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^12.1.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  responsive_sizer: ^3.2.0
  line_icons: ^2.0.3
  get: ^4.6.6
  equatable: ^2.0.5
  flutter_slidable: ^1.2.0
  flutter_slider_drawer: ^2.1.3
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.3
  meta: ^1.10.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
